name: Run WorldQuant Alpha Miner

on:
  schedule:
    # Chạy mỗi ngày vào lúc 00:00 UTC (5:00 AM ICT/GMT+7)
    # Bạn có thể điều chỉnh lịch trình theo ý muốn
    - cron: '0 0 * * *' 
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub Actions tab

jobs:
  build-and-run:
    runs-on: ubuntu-latest # Sử dụng môi trường Ubuntu mới nhất

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: WorldQuant-master # Checkout repository vào thư mục WorldQuant-master

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Cập nhật phiên bản Python để nhất quán

    - name: Install dependencies
      working-directory: WorldQuant-master # Đặt thư mục làm việc cho bước này
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Đường dẫn tương đối từ working-directory

    - name: Create sensitive files from secrets
      working-directory: WorldQuant-master # Create files in the repository root
      run: |
        echo '${{ secrets.WORLDQUANT_CREDENTIALS_JSON }}' > credential.json
        echo '${{ secrets.GOOGLE_API_KEYS_JSON }}' > keyapi.json
        echo '${{ secrets.GOOGLE_SHEET_CREDENTIALS }}' > apisheet.json # Sử dụng đúng tên secret: GOOGLE_SHEET_CREDENTIALS

    - name: Run Alpha Miner Script
      working-directory: WorldQuant-master # Đặt thư mục làm việc cho script
      env:
        GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS_JSON }} # Sử dụng secret JSON cho biến môi trường
        # GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }} # Không cần thiết nếu apisheet.json được tạo
        # WORLDQUANT_USERNAME: ${{ secrets.WORLDQUANT_USERNAME }} # Không cần thiết nếu credential.json được tạo
        # WORLDQUANT_PASSWORD: ${{ secrets.WORLDQUANT_PASSWORD }} # Không cần thiết nếu credential.json được tạo
        INDEX_KEY: ${{ secrets.INDEX_KEY }}
        FILE_PDF_PATH: ${{ secrets.FILE_PDF_PATH }} # Có thể để trống nếu không có
        FILE_SUB_HYPOTHESIS_PATH: ${{ secrets.FILE_SUB_HYPOTHESIS_PATH }} # Ví dụ: Finding Alpha - Sub Hypothesis.csv
        MAX_RUN_CYCLES: ${{ secrets.MAX_RUN_CYCLES }} # Số chu kỳ chạy tối đa (ví dụ: 0 để chạy vô hạn trong giới hạn 6h)
        SLEEP_BETWEEN_CYCLES_SECONDS: ${{ secrets.SLEEP_BETWEEN_CYCLES_SECONDS }} # Thời gian chờ giữa các chu kỳ (giây)
      run: |
        python genai_v2/genai.py # Đường dẫn tương đối từ working-directory
