name: Run WorldQuant Alpha Miner

on:
  schedule:
    # Chạy mỗi ngày vào lúc 00:00 UTC (5:00 AM ICT/GMT+7)
    # Bạn có thể điều chỉnh lịch trình theo ý muốn
    - cron: '0 0 * * *' 
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub Actions tab

jobs:
  build-and-run:
    runs-on: ubuntu-latest # Sử dụng môi trường Ubuntu mới nhất

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: WorldQuant-master # Checkout repository vào thư mục WorldQuant-master

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Đảm bảo phiên bản Python tương thích với requirements.txt

    - name: Install dependencies
      working-directory: WorldQuant-master # Đặt thư mục làm việc cho bước này
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Đường dẫn tương đối từ working-directory

    - name: Run Alpha Miner Script
      working-directory: WorldQuant-master # Đặt thư mục làm việc cho script
      env:
        GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS }}
        GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}
        WORLDQUANT_USERNAME: ${{ secrets.WORLDQUANT_USERNAME }}
        WORLDQUANT_PASSWORD: ${{ secrets.WORLDQUANT_PASSWORD }}
        INDEX_KEY: ${{ secrets.INDEX_KEY }}
        FILE_PDF_PATH: ${{ secrets.FILE_PDF_PATH }} # Có thể để trống nếu không có
        FILE_SUB_HYPOTHESIS_PATH: ${{ secrets.FILE_SUB_HYPOTHESIS_PATH }} # Ví dụ: Finding Alpha - Sub Hypothesis.csv
      run: |
        python genai_v1/genai.py # Đường dẫn tương đối từ working-directory
